version: '3'
services:
  validate:
    image: hashicorp/terraform:0.12.28
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - GIT_SSH_COMMAND=ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
      - TF_INPUT=0
    volumes:
      - .:/workdir
      - /mnt/nfs-drive-1:/mnt/nfs-drive-1
    working_dir: /workdir
    entrypoint: sh
    command: -c "scripts/validate.sh"

  destroy:
    image: hashicorp/terraform:0.12.28
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - GIT_SSH_COMMAND=ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
      - TF_INPUT=0
    volumes:
      - .:/workdir
      - /mnt/nfs-drive-1:/mnt/nfs-drive-1
    working_dir: /workdir
    entrypoint: sh
    command: -c "scripts/destroy.sh"

  build:
    image: hashicorp/terraform:0.12.28
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - GIT_SSH_COMMAND=ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
      - TF_INPUT=0
    volumes:
      - .:/workdir
      - /mnt/nfs-drive-1:/mnt/nfs-drive-1
    working_dir: /workdir
    entrypoint: sh
    command: -c "scripts/build.sh"
