#steps:  
#  - label: ":bowtie: :github: Read credentials"
#    command: 
#      - "ls -la /workdir"
#      - "wget http://192.168.1.30:8000/scripts/terraform_vcenter_cred.sh -O /tmp/terraform_vcenter_cred.sh && chmod u+x /tmp/terraform_vcenter_cred.sh && . /tmp/terraform_vcenter_cred.sh && env"
#      - "wget http://192.168.1.30:8000/scripts/terraform_vcenter_cred.sh -O /tmp/terraform_vcenter_cred.sh && chmod u+x /tmp/terraform_vcenter_cred.sh && /tmp/terraform_vcenter_cred.sh && cd /workdir && terraform init && terraform destroy -input=false -var template_name=centos-base -var vm_name=centos-vm -var ip_address=192.168.1.60  -var vsphere_datastore=esx-nfs-1 -auto-approve"
#      - "wget http://192.168.1.30:8000/scripts/terraform_vcenter_cred.sh -O /tmp/terraform_vcenter_cred.sh && chmod u+x /tmp/terraform_vcenter_cred.sh && /tmp/terraform_vcenter_cred.sh && cd /workdir && terraform init && terraform apply -input=false -var template_name=centos-base -var vm_name=centos-vm -var ip_address=192.168.1.60  -var vsphere_datastore=esx-nfs-1 -auto-approve"
#    plugins:
#      - docker#v3.5.0:
#          image: "een625/docker-builder:latest"
#          always-pull: true
#          volumes:
#            - "/mnt/tf-centos-base:/mnt/tf-centos-base"
#          #propagate-environment: true
#    agents:
#      docker: "true"
#      home: "true"

steps:
  - command: "ls /workdir"
    plugins:
      - docker#v3.5.0:
          image: "een625:docker-builder"
    agents:
      docker: "true"
      home: "true"