env:
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
  - name: "docker-compose test"
    plugins:
      docker-compose:
        pull: terraform
        run: terraform
    agents:
      vm: "true"
      home: "true"