steps:
  
  - label: ":bowtie: :github: Read credentials"
    command: 
      - "wget http://192.168.1.30:8000/scripts/terraform_vcenter_cred.sh -O /tmp/terraform_vcenter_cred.sh && chmod u+x /tmp/terraform_vcenter_cred.sh && /tmp/terraform_vcenter_cred.sh && terraform init && terraform destroy -input=false -var template_name=centos-base -var vm_name=centos-vm -var ip_address=192.168.1.60  -var vsphere_datastore=esx-nfs-1 -auto-approve"
      - "wget http://192.168.1.30:8000/scripts/terraform_vcenter_cred.sh -O /tmp/terraform_vcenter_cred.sh && chmod u+x /tmp/terraform_vcenter_cred.sh && /tmp/terraform_vcenter_cred.sh && terraform init && terraform apply -input=false -var template_name=centos-base -var vm_name=centos-vm -var ip_address=192.168.1.60  -var vsphere_datastore=esx-nfs-1 -auto-approve"
    plugins:
      - docker#v3.5.0:
          image: "een625/docker-bkagent:latest"
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    agents:
      home: "true"
