steps:
  - label: ":hammer: Read credentials"
    command: wget -P /tmp http://192.168.1.30:8000/scripts/vcenter_cred && chmod u+x /tmp/vcenter_cred && /tmp/vcenter_cred

  - wait

  - label: ":package: Build centos-base image"
    command: terraform init && terraform apply -input=false -var template_name=centos-base -var vm_name=test -var ip_address=192.168.1.60 -var vsphere_password=${VCENTER_PASSWORD} -var vsphere_datastore=esx-nfs-1 -auto-approve